### ISSUE TITLE
Workspace may become unsuable when generating new devel images

### ISSUE THREAD

**Issue by planthaber** [dfki-ric/docker_image_development#43]
Due to the username change in https://github.com/dfki-ric/docker_image_development/pull/35 existing devel workspaces, that are saving paths to the home directory become invalid because the new user "dockeruser" also has a new home dir (having the same uid).

This could be solved setting up the workspace from scratch or with a workaround by adding a symlink as in the previous releases:

```Dockerfile
RUN ln -s /home/dockeruser/ /home/devel
RUN chown dockeruser:dockeruser-group /home/devel
```

When using the workaround it could be part of the base images of individual devel images. 

I'd put it into the devel image Dockerfile so every user can do it on its own, if nessecary.
Perhaps we could put it into the 02_devel_image/Dockerfile template and comment it so it is not executed by default).

**Comment by 0Nel** [comment]
Good catch! We should consider a troubleshooting or how to upgrade section somewhere in the docs to document workarounds like this. I think workarounds and fixes that need to be done manually by project maintainers need to be explained. Otherwise people might get afraid of upgrading from upstream, especially if it contains major release updates.

**Comment by planthaber** [comment]
Looks like to repair the workspace, you have to call:

* rm /opt/workspace/autoproj/overrides.d/100_dist_override-ubuntu-20.04-overrides.yml
* ruby autoproj_bootstrap (if it fails, try again)
